/**
 * Regenerates theme.json and _ds_manifest.json from the real source.
 *
 *   node design-system/build.mjs
 *
 * Tokens are read out of ../src/index.css — never hand-written here — so the
 * machine-readable record of the theme cannot drift from the stylesheet the app
 * actually loads. Cards are read from the `@dsCard` comment on the first line of
 * each preview page, so adding a preview is one file, not two.
 *
 * Run this after changing a token or adding a preview, and commit the result.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const cssPath = path.join(here, "..", "src", "index.css");

// --- tokens ----------------------------------------------------------------

/** Only the light `:root` block. The dark block redefines the same names. */
function readTokens(css) {
  const start = css.indexOf(":root {");
  if (start === -1) throw new Error("no :root block in src/index.css");
  const end = css.indexOf("\n}", start);
  const block = css.slice(start, end);

  const tokens = [];
  for (const line of block.split("\n")) {
    const m = line.match(/^\s*(--[\w-]+)\s*:\s*([^;]+);/);
    if (!m) continue;
    const [, name, raw] = m;
    tokens.push({ name, value: raw.trim(), kind: kindOf(name), definedIn: "styles.css" });
  }
  return tokens;
}

function kindOf(name) {
  if (name.startsWith("--space")) return "space";
  if (name.startsWith("--radius")) return "radius";
  if (name.startsWith("--shadow")) return "shadow";
  if (name.startsWith("--font")) return "font";
  return "color";
}

// --- cards -----------------------------------------------------------------

/** `<!-- @dsCard group="…" name="…" subtitle="…" viewport="…" -->` on line 1. */
function readCard(file) {
  const first = fs.readFileSync(file, "utf8").split("\n", 1)[0];
  if (!first.includes("@dsCard")) return null;
  const attr = (k) => first.match(new RegExp(`${k}="([^"]*)"`))?.[1];
  return {
    path: path.relative(here, file).split(path.sep).join("/"),
    group: attr("group") ?? "Components",
    viewport: attr("viewport") ?? "640x480",
    subtitle: attr("subtitle") ?? "",
    name: attr("name") ?? path.basename(file, ".html"),
  };
}

function previewFiles() {
  return ["foundations", "components"]
    .flatMap((dir) => {
      const d = path.join(here, dir);
      return fs.existsSync(d)
        ? fs.readdirSync(d).filter((f) => f.endsWith(".html")).map((f) => path.join(d, f))
        : [];
    })
    .sort();
}

// --- write -----------------------------------------------------------------

const css = fs.readFileSync(cssPath, "utf8");
const tokens = readTokens(css);
const cards = previewFiles().map(readCard).filter(Boolean);

const groupOrder = { Foundations: 0, Components: 1, Theme: 2 };
cards.sort(
  (a, b) => (groupOrder[a.group] ?? 9) - (groupOrder[b.group] ?? 9) || a.name.localeCompare(b.name),
);

fs.writeFileSync(
  path.join(here, "_ds_manifest.json"),
  JSON.stringify(
    {
      namespace: "Roamance",
      components: [],
      startingPoints: [],
      cards,
      templates: [],
      hasThumbnailHtml: fs.existsSync(path.join(here, "thumbnail.html")),
      globalCssPaths: ["styles.css"],
      tokens,
      source: "generated by design-system/build.mjs from src/index.css",
    },
    null,
    2,
  ) + "\n",
);

// styles.css is GENERATED from src/index.css rather than importing it, so the
// bundle stays self-contained when only design-system/ is uploaded — an
// @import pointing at ../src would resolve to nothing there. Generating it
// keeps the no-drift property that the import was there to provide.
fs.writeFileSync(
  path.join(here, "styles.css"),
  `/* GENERATED FILE — do not edit.\n` +
    ` *\n` +
    ` * Written by design-system/build.mjs from src/index.css, which is the single\n` +
    ` * source of truth for every Roamance token and component style. Edit that file\n` +
    ` * and re-run \`node design-system/build.mjs\`; anything you change here is lost.\n` +
    ` */\n\n` +
    css,
);

const byKind = (k) => Object.fromEntries(tokens.filter((t) => t.kind === k).map((t) => [t.name, t.value]));

fs.writeFileSync(
  path.join(here, "theme.json"),
  JSON.stringify(
    {
      name: "Roamance",
      description:
        "Warm paper ground, coral for action, teal for focus, gold for money. Soft radii and accent-tinted shadows.",
      generatedFrom: "src/index.css",
      fonts: { heading: "Work Sans", body: "Work Sans" },
      colors: byKind("color"),
      space: byKind("space"),
      radius: byKind("radius"),
      shadow: byKind("shadow"),
      type: byKind("font"),
    },
    null,
    2,
  ) + "\n",
);

// Adherence rules. The token list is generated so it cannot fall behind the
// stylesheet — that is the whole point of checking adherence at all.
fs.writeFileSync(
  path.join(here, "_adherence.oxlintrc.json"),
  JSON.stringify(
    {
      plugins: ["react", "import"],
      rules: {
        "no-restricted-syntax": [
          "warn",
          {
            selector: "Literal[value=/#[0-9a-fA-F]{3,8}\\b/]",
            message: "Raw hex colour — use a Roamance colour token via var(). See docs/THEME.md.",
          },
          {
            selector: "Literal[value=/\\b\\d+px\\b/]",
            message: "Raw px value — use a --space-* or --radius-* token via var().",
          },
          {
            selector: "Literal[value=/font-family\\s*:\\s*(?!['\"]?(?:Work Sans))/i]",
            message: "Font not provided by the design system. Available: Work Sans.",
          },
        ],
      },
      "x-omelette": {
        components: {},
        tokens: tokens.map((t) => t.name).sort(),
      },
    },
    null,
    2,
  ) + "\n",
);

console.log(
  `theme.json + _ds_manifest.json + _adherence.oxlintrc.json: ${tokens.length} tokens, ${cards.length} cards`,
);
